---
accent_color: "#00BFFF"
lang: en-US
title: Prayer in Life
description: Short, daily meditations on God's Word that guide us into Scripture-based
  Prayer
baseurl: ''
url: https://scriptor-jekyll.netlify.com
permalink: "/:title"
favicon: "/images/https___bucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com_public_images_17f6fead-8333-4e07-8cca-e5b0587ac752_256x256.png"
google_analytics: ''
disqus: justgoodthemes
navigation:
- text: Home
  url: "/"
- text: About
  url: "/about/"
- text: Tags
  url: "/tags/"
footer:
  content: "© Jonathan Santiago all rights reserved. Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true
plugins:
- jekyll-paginate
paginate: 3
paginate_path: "/page:num/"
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
