---
accent_color: "#191970"
lang: en-US
title: PrayStack
description: 'Are your prayers just lists of requests to God? Rethink Prayer with
  PrayStack. PrayStack is a free resource that guides you through these different
  types of prayers: Adoration, Confession, Renewal, Petition, Intercession, Affirmation,
  and Thanksgiving.'
baseurl: ''
url: https://scriptor-jekyll.netlify.com
permalink: "/:title"
favicon: images/favicon.png
google_analytics: ''
disqus: justgoodthemes
navigation:
- text: Home
  url: "/"
- text: About
  url: "/about/"
- text: Tags
  url: "/tags/"
footer:
  content: "© Jonathan Santiago all rights reserved. Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true
plugins:
- jekyll-paginate
paginate: 3
paginate_path: "/page:num/"
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
